### ISSUE TITLE
Category listing with description

### ISSUE THREAD

**Issue by torvista** [lat9/zen_short_codes#2]
Is there are core file option to show category descriptions when in a list like so:
![2024-07-21 17_37_56-Steve BCN BCN - Eazi-Grip Racing Products - Motorvista, Motorcycle Accessories S](https://github.com/user-attachments/assets/50f6e32d-1a8f-4df0-ad26-2adc4b0057a4)

If there is, I can't find it to test.

**Comment by lat9** [comment]
Not that I'm aware of ... and off-topic!

**Comment by torvista** [comment]
Note the unconverted shortcode in the first description.
For short codes to work on the these subcategory descriptions, it needs to watch 'NOTIFY_TPL_COLUMNAR_DISPLAY_START' and parse $list_box_contents.

**Comment by lat9** [comment]
What setting controls the inclusion of the categories' description?  I'm presuming that that's a category-index listing page, please advise.

**Comment by torvista** [comment]
When there are subcategories listed 

includes\modules\pages\index\main_template_vars.php

uses

  $tpl_page_body = 'tpl_index_categories.php';

which eventually uses
 
\includes\templates\TEMPLATE\common\tpl_columnar_display.php

when the array can be parsed by 'NOTIFY_TPL_COLUMNAR_DISPLAY_START'

**Comment by lat9** [comment]
Right, but is there a setting that identifies the number of characters of a category's description to be used for the display.

**Comment by torvista** [comment]
Digging some more, the meat is put on the array bones in modules/category_row in which I discover that the text side is something I've added, so maybe can leave this to one side now:
but 
function zen_get_category_description
could have a notifier for this purpose.
